### ISSUE TITLE
Channel width parameter

### ISSUE THREAD

**Issue by r3a1d3a1** [sdelrio/rpi-hostap#17]
This is great. 
One last thing to make it perfect would be to allow changing channel width to 40MHz or 80MHz (if using a 5GHz channel).
Thanks!

**Comment by sdelrio** [comment]
80MHZ needs 802.11ac. And on 5GHz is best to leave the width to auto. If you force 80MHz and have neigbours with what wide, is impossible to not have interference. on that band the adapter and the AP usually talk to get the best.

**Comment by r3a1d3a1** [comment]
I live in the city and it's full of interference on every single channel :) 
Forcing higher bandwidth is my best bet.

**Comment by sdelrio** [comment]
Belive me, is your worst bet, the the thinner channel in that case.

  Saludos

  Sergio del Río


<http://www.flickr.com/photos/of_the_river/>

**Comment by r3a1d3a1** [comment]
You're wrong.

**Comment by sdelrio** [comment]
I have 10 years professional experience with Wireless

Good luck forcing 80Ghz on DFS channels.

https://en.wikipedia.org/wiki/List_of_WLAN_channels#5_GHz_or_5.9_GHz_(802.11a/h/j/n/ac/ax)

**Comment by r3a1d3a1** [comment]
Seemingly, that 10 yrs was wasted :)
