### ISSUE TITLE
DHCP DNS as parameter

### ISSUE THREAD

**Issue by lorenzo-pizzari** [sdelrio/rpi-hostap#7]
Hi,

First of all thank you for your project. Is exactly what i'm looking for my situation (crappy wifi router ;) ).

I'm setting up the Rasp as an AP and a part of a bigger project where i also want to implement a local DNS Server. On my fork i've added the DNS configuration of dhcpd as optional parameter.

If you think that can be interesting for the project i can make a pull request. Let me know!

**Comment by sdelrio** [comment]
Yes, I think is useful, just a note: on your fork it looks like you mixed on the same commit of the dns changes with a modification on the README, but you can make the PR I was planning on update the README anyway someday, but just got busy these days.
